### ISSUE TITLE
TypeError: tracer.info is not a function

### ISSUE THREAD

**Issue by dubanflorin** [roytan883/pomelo-rpc-ws#3]
I keep getting this and it's crashing my server

> TypeError: tracer.info is not a function
at doFilter (/var/www/repo/game-server/node_modules/pomelo-rpc-ws/lib/rpc-client/mailstation.js:345:12)
at /var/www/repo/game-server/node_modules/pomelo-rpc-ws/lib/rpc-client/mailstation.js:256:7
at Object.exp.invokeCallback (/var/www/repo/game-server/node_modules/pomelo-rpc-ws/lib/util/utils.js:5:8)
at WebSocket.<anonymous> (/var/www/repo/game-server/node_modules/pomelo-rpc-ws/lib/rpc-client/mailboxes/websocket-mailbox.js:132:13)
at WebSocket.emit (events.js:223:5)
at WebSocket.EventEmitter.emit (domain.js:475:20)
at WebSocket.emitClose (/var/www/repo/game-server/node_modules/pomelo-rpc-ws/node_modules/ws/lib/WebSocket.js:213:10)
at /var/www/repo/game-server/node_modules/pomelo-rpc-ws/node_modules/ws/lib/WebSocket.js:195:41
at Receiver.cleanup (/var/www/repo/game-server/node_modules/pomelo-rpc-ws/node_modules/ws/lib/Receiver.js:520:15)
at WebSocket.finalize (/var/www/repo/game-server/node_modules/pomelo-rpc-ws/node_modules/ws/lib/WebSocket.js:195:22)

Can you help me? Thank you.

**Comment by dubanflorin** [comment]
I looked into the code and it seems there is is a typo.
https://github.com/roytan883/pomelo-rpc-ws/blob/master/lib/rpc-client/mailboxes/ws-mailbox.js#L73
https://github.com/roytan883/pomelo-rpc-ws/blob/master/lib/rpc-client/mailboxes/websocket-mailbox.js#L132
the call from the websocket version is missing tracer param
